# Generated by Django 5.2.9 on 2026-02-09 16:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('excerpt', models.TextField(blank=True)),
                ('published_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('quote', 7), ('code', 10), ('embed', 11), ('call_to_action', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('blog.models.blocks.ParagraphBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('blog.models.blocks.QuoteBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 30, 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'required': True}), 10: ('wagtail.blocks.StructBlock', [[('language', 8), ('code', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 13: ('wagtail.blocks.URLBlock', (), {'required': True}), 14: ('wagtail.blocks.StructBlock', [[('text', 12), ('url', 13)]], {})})),
                ('meta_description', models.TextField(blank=True, help_text='150-160 characters recommended. Leave blank to use excerpt.')),
                ('schema_type', models.CharField(blank=True, help_text='Examples: Article, BlogPosting, NewsArticle.', max_length=50)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Recommended size: 1200x630px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
