# Generated by Django 5.2.9 on 2026-02-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords. Leave blank to use site defaults.', max_length=255),
        ),
    ]
